services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
      # Supprime les args de proxy si présents
      # args:
      #   HTTP_PROXY: ""
      #   HTTPS_PROXY: ""
    ports:
      - "${SYMFONY_HTTP_PORT}:80"
      - "${SYMFONY_HTTPS_PORT}:443"
    volumes:
      - .:/app
      - vendor:/app/vendor
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      DEFAULT_URI: ${DEFAULT_URI}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      # Forcer Docker à ne pas utiliser de proxy
      NO_PROXY: "*"
    container_name: symfony_app_nandia
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: symfony_postgres_nandia
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: symfony_pgadmin_nandia
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pgdata:
  pgadmin_data:
  vendor:
