<?php
// src/DataFixtures/CardFixtures.php

namespace App\DataFixtures;

use App\Entity\Card;
use App\Entity\Theme;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class CardFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        // ── Thèmes ────────────────────────────────────────────────────────────
        //
        // Chaque thème contient :
        //   - name, colorCode, description, backgroundImage (asset local Flutter)
        //   - cards[]      : questions type "question" (simultané)
        //   - challenges[] : questions type "challenge" (tour à tour / défi)
        //
        $themes = [
            // ── 1. COUPLE ────────────────────────────────────────────────────
            [
                'name'            => 'Couple',
                'colorCode'       => '#ec1380',
                'description'     => 'Explorez la dynamique de votre couple, ses forces et ses fragilités.',
                'backgroundImage' => 'assets/images/themes/couple.jpg',
                'cards' => [
                    "Quelle est la chose la plus folle que tu aimerais faire avec moi ?",
                    "Quel est ton rêve d'avenir en tant que couple ?",
                    "Qu'est-ce que tu attends de moi dans les moments difficiles ?",
                    "Comment définirais-tu une relation idéale ?",
                    "Quelle est la chose la plus importante que tu veux que je sache sur toi ?",
                    "Quel est ton plus grand espoir pour notre relation ?",
                    "Qu'est-ce qui te rend le plus heureux/heureuse avec moi ?",
                    "Quel est ton plus grand défi en tant que couple ?",
                    "Qu'est-ce que tu aimerais que l'on fasse plus souvent ensemble ?",
                    "Quelle est ta promesse pour l'avenir de notre relation ?",
                    "Quel souvenir partagé te fait encore sourire aujourd'hui ?",
                    "Qu'est-ce que tu apprécies le plus chez moi en ce moment ?",
                    "Si on pouvait tout recommencer, tu changerais quoi ?",
                    "C'est quoi ton rêve que tu n'as jamais osé me partager ?",
                    "Qu'est-ce qui te manquerait le plus si on se séparait d'un jour ?",
                    "Quelle est la décision la plus difficile que nous ayons prise ensemble ?",
                    "Qu'est-ce que notre couple t'a appris sur toi-même ?",
                    "Y a-t-il quelque chose que tu faisais avant nous et que tu regrettes d'avoir abandonné ?",
                    "Comment sais-tu que je t'aime vraiment ?",
                    "Quelle est la plus belle surprise que tu m'aies faite ou que j'aurais pu te faire ?",
                    "Qu'est-ce qui te fait te sentir vu(e) et compris(e) par moi ?",
                    "Si notre couple était un film, quel genre serait-il ?",
                    "Qu'est-ce que tu préfères dans notre routine quotidienne ?",
                    "Quelle conversation difficile t'a le plus rapproché(e) de moi ?",
                    "Qu'est-ce que tu ne changerais pour rien au monde dans notre relation ?",
                    "As-tu l'impression qu'on s'écoute vraiment l'un l'autre ?",
                    "Quel petit geste du quotidien de ma part compte le plus pour toi ?",
                    "Qu'est-ce qui te retient dans les moments où tu veux partir ?",
                    "Si tu devais décrire notre amour en une chanson, laquelle choisirais-tu ?",
                    "Quelle qualité de notre relation veux-tu développer cette année ?",
                ],
                'challenges' => [
                    "Dis à ton partenaire une chose qu'il/elle fait qui te touche particulièrement.",
                    "Décris le moment où tu t'es senti(e) le plus proche de ton partenaire.",
                    "Raconte à voix haute votre première vraie dispute et comment elle vous a changés.",
                    "Échangez chacun un secret que vous n'avez jamais osé partager.",
                    "Dites à l'autre ce que vous admirez en lui/elle sans jamais le dire assez.",
                ],
            ],

            // ── 2. VALEURS ────────────────────────────────────────────────────
            [
                'name'            => 'Valeurs',
                'colorCode'       => '#3498db',
                'description'     => 'Explorez les valeurs et croyances fondamentales qui guident votre relation.',
                'backgroundImage' => 'assets/images/themes/valeurs.jpg',
                'cards' => [
                    "Quelle est ta valeur la plus importante dans une relation ?",
                    "Qu'est-ce qui te motive le plus dans la vie ?",
                    "Quelle est ta croyance la plus profonde sur l'amour ?",
                    "Quel est ton principe moral le plus incontournable ?",
                    "Comment définis-tu la fidélité ?",
                    "Quelle est la chose la plus importante pour toi dans la vie ?",
                    "Quelle est ton idée de la liberté dans un couple ?",
                    "Qu'est-ce que tu ne supporterais pas chez un partenaire ?",
                    "Quel est ton rêve de vie idéale ?",
                    "Quelle est ta vision de la réussite personnelle ?",
                    "Est-ce que l'honnêteté totale est toujours la meilleure option pour toi ?",
                    "Qu'est-ce qui te ferait trahir une valeur que tu considères essentielle ?",
                    "Comment prends-tu une décision morale difficile ?",
                    "Quelle valeur commune est le fondement de notre couple selon toi ?",
                    "Y a-t-il une valeur que tu as changée grâce à notre relation ?",
                    "Qu'est-ce que la bienveillance signifie concrètement pour toi au quotidien ?",
                    "Comment gères-tu un conflit de valeurs avec quelqu'un que tu aimes ?",
                    "Est-ce que tu penses qu'on peut aimer durablement quelqu'un qui ne partage pas nos valeurs ?",
                    "Quel modèle de couple as-tu grandi en voyant et quel impact a-t-il eu ?",
                    "Qu'est-ce que le respect mutuel veut dire en pratique pour toi ?",
                    "Y a-t-il une valeur que tu as héritée de ta famille mais que tu remets en question ?",
                    "Comment distingues-tu ce qui est important de ce qui est urgent dans ta vie ?",
                    "Est-ce que la loyauté peut avoir des limites selon toi ?",
                    "Qu'est-ce que la justice dans une relation de couple ?",
                    "Quelle valeur voudrais-tu transmettre à tes enfants ou à la prochaine génération ?",
                    "Est-ce que la générosité est une valeur ou un comportement pour toi ?",
                    "Qu'est-ce que la confiance — se gagne-t-elle ou s'accorde-t-elle d'emblée ?",
                    "Quelle est la différence entre une valeur et une habitude pour toi ?",
                    "Est-ce qu'on peut changer de valeurs fondamentales avec l'âge ?",
                    "Qu'est-ce que l'autonomie dans un couple représente pour toi ?",
                ],
                'challenges' => [
                    "Citez une valeur que vous partagez et expliquez comment elle se manifeste dans votre quotidien.",
                    "Exprime une conviction que tu n'as jamais partagée avec ton partenaire.",
                    "Chacun liste ses 3 valeurs prioritaires — comparez et discutez les différences.",
                    "Donnez un exemple récent où vous avez agi en accord avec une de vos valeurs malgré la difficulté.",
                    "Imaginez un dilemme moral et exposez chacun comment vous le résoudriez.",
                ],
            ],

            // ── 3. SEXUALITÉ ─────────────────────────────────────────────────
            [
                'name'            => 'Sexualité',
                'colorCode'       => '#e74c3c',
                'description'     => 'Explorez la sexualité et l\'intimité dans votre relation en toute confiance.',
                'backgroundImage' => 'assets/images/themes/sexualite.jpg',
                'cards' => [
                    "Qu'est-ce que l'intimité signifie pour toi ?",
                    "Quel est ton fantasme le plus secret ?",
                    "Qu'est-ce qui te fait te sentir le plus proche de moi ?",
                    "Comment décrirais-tu ta vie sexuelle idéale ?",
                    "Qu'est-ce que tu aimes que je te fasse ?",
                    "Quel est ton moment le plus intime avec moi ?",
                    "Qu'est-ce que tu aimerais que l'on explore ensemble ?",
                    "Qu'est-ce qui te rend vulnérable avec moi ?",
                    "Quel est ton désir le plus profond ?",
                    "Qu'est-ce que tu voudrais que l'on ose ensemble ?",
                    "Y a-t-il quelque chose que tu hésites à me demander par peur de ma réaction ?",
                    "Qu'est-ce qui déclenche le plus ton désir pour moi ?",
                    "Comment préfères-tu qu'on recréé de la tension entre nous après une période calme ?",
                    "Qu'est-ce que tu associes à la séduction dans notre couple ?",
                    "Est-ce que tu te sens libre d'exprimer tes désirs avec moi ?",
                    "Qu'est-ce qui te coupe le plus l'envie, et comment puis-je t'aider ?",
                    "Y a-t-il un endroit ou un contexte insolite qui t'attire ?",
                    "Comment est-ce que tu vis le fait de vieillir et l'impact sur ton rapport à ton corps ?",
                    "Est-ce que tu penses que la sexualité peut être un langage de réconciliation ?",
                    "Qu'est-ce que tu aimerais qu'on fasse plus souvent dans notre intimité ?",
                    "Est-ce que la communication pendant l'acte est importante pour toi ?",
                    "Y a-t-il un fantasme que tu considères trop tabou pour le partager ?",
                    "Comment maintiens-tu le désir quand la routine s'installe ?",
                    "Qu'est-ce qui te fait te sentir désirable ?",
                    "Est-ce que la sexualité a changé pour toi depuis le début de notre relation ?",
                    "Qu'est-ce que la confiance change dans ton rapport à l'intimité ?",
                    "Y a-t-il quelque chose que tu n'as jamais essayé mais qui t'intrigue ?",
                    "Comment gères-tu les moments où vos envies ne sont pas synchronisées ?",
                    "Qu'est-ce que tu voudrais améliorer dans notre vie intime ?",
                    "Est-ce que tu penses qu'une relation peut survivre à une longue panne d'intimité ?",
                ],
                'challenges' => [
                    "Dis à ton partenaire ce qui te rend le plus à l'aise avec lui/elle physiquement.",
                    "Propose une nouvelle chose que vous n'avez jamais tentée ensemble.",
                    "Chacun dit à l'autre ce qu'il/elle apprécie le plus dans votre vie intime.",
                    "Partagez chacun une limite que vous avez et expliquez pourquoi elle est importante.",
                    "Décrivez à voix haute votre soirée idéale ensemble, des préliminaires à la fin.",
                ],
            ],

            // ── 4. PASSÉ ─────────────────────────────────────────────────────
            [
                'name'            => 'Passé',
                'colorCode'       => '#f39c12',
                'description'     => 'Explorez le passé et les expériences qui ont façonné votre relation.',
                'backgroundImage' => 'assets/images/themes/passe.jpg',
                'cards' => [
                    "Quel souvenir d'enfance te rend nostalgique ?",
                    "Quelle est la chose la plus difficile que tu aies traversée ?",
                    "Quelle émotion ressens-tu le plus souvent ?",
                    "Qu'est-ce que ton passé t'a appris sur toi ?",
                    "Quelle est ton expérience la plus marquante avant moi ?",
                    "Quel est ton plus grand regret ?",
                    "Qu'est-ce que tu as du mal à pardonner ?",
                    "Quelle émotion aimerais-tu que je comprenne mieux ?",
                    "Quel souvenir partagé avec moi est le plus précieux ?",
                    "Qu'est-ce que tu veux guérir ensemble ?",
                    "Comment ton enfance influence-t-elle ta façon d'aimer aujourd'hui ?",
                    "Y a-t-il quelqu'un de ton passé qui t'a profondément marqué(e) — positivement ou négativement ?",
                    "Quelle erreur passée t'a le plus appris ?",
                    "Y a-t-il un chapitre de ta vie que tu n'as encore jamais vraiment raconté ?",
                    "Quel événement t'a fait devenir la personne que tu es aujourd'hui ?",
                    "Y a-t-il quelque chose dans ton histoire familiale que tu portes encore ?",
                    "Quel âge as-tu eu le plus de mal à traverser et pourquoi ?",
                    "Y a-t-il une relation passée qui t'a durablement changé(e) ?",
                    "Comment as-tu appris à faire confiance après avoir été blessé(e) ?",
                    "Qu'est-ce que tu aurais aimé que quelqu'un te dise quand tu avais 15 ans ?",
                    "Quel souvenir heureux veux-tu préserver coûte que coûte ?",
                    "Y a-t-il quelque chose que tu regrettes de ne pas avoir dit à quelqu'un ?",
                    "Comment ta relation avec tes parents a-t-elle influencé ta vision du couple ?",
                    "Quelle période de ta vie était la plus dure, et qu'est-ce qui t'a aidé à la traverser ?",
                    "Y a-t-il un deuil — d'une personne, d'une relation, d'un rêve — que tu portes encore ?",
                    "Quel événement t'a rendu(e) plus fort(e) ?",
                    "Comment les blessures du passé se manifestent-elles parfois dans notre relation ?",
                    "Qu'est-ce que tu as pardonné — à toi-même ou à quelqu'un d'autre ?",
                    "Y a-t-il un moment de ta vie où tu aurais aimé que je sois là ?",
                    "Quel souvenir de nous deux gardes-tu précieusement sans l'avoir jamais dit ?",
                ],
                'challenges' => [
                    "Partage un souvenir d'enfance que tu n'as jamais raconté à ton partenaire.",
                    "Décris le moment où tu as réalisé que ton partenaire était la bonne personne.",
                    "Montre à ton partenaire une vieille photo de toi et raconte l'histoire derrière.",
                    "Parle d'une personne du passé qui t'a appris quelque chose d'essentiel sur toi.",
                    "Raconte la journée la plus difficile de ta vie et comment tu t'en es sorti(e).",
                ],
            ],

            // ── 5. PROJETS ────────────────────────────────────────────────────
            [
                'name'            => 'Projets',
                'colorCode'       => '#2ecc71',
                'description'     => 'Explorez vos projets et aspirations pour l\'avenir de votre relation.',
                'backgroundImage' => 'assets/images/themes/projets.jpg',
                'cards' => [
                    "Quel est ton rêve le plus fou pour nous ?",
                    "Où te vois-tu dans 5 ans avec moi ?",
                    "Quel est le projet que tu aimerais réaliser ensemble ?",
                    "Qu'est-ce que tu veux accomplir avant tout ?",
                    "Quelle est ta vision de notre vie future ?",
                    "Quel est ton plus grand objectif personnel ?",
                    "Qu'est-ce que tu aimerais apprendre ensemble ?",
                    "Quel est ton endroit préféré pour voyager avec moi ?",
                    "Qu'est-ce que tu veux construire avec moi ?",
                    "Quelle est ta définition du succès en couple ?",
                    "Y a-t-il un projet que tu repousses depuis trop longtemps ?",
                    "Si l'argent n'était pas un obstacle, que ferait-on dans la prochaine année ?",
                    "Quel pays aimerais-tu qu'on explore ensemble et pourquoi ?",
                    "Est-ce que tu envisages de changer de ville ou de mode de vie un jour ?",
                    "Quel projet vous permettrait de mieux vous connaître en tant que couple ?",
                    "Si vous créiez une entreprise ensemble, ce serait quoi ?",
                    "Quel défi physique ou sportif aimerais-tu qu'on relève ensemble ?",
                    "As-tu des projets liés à la famille — avoir des enfants, s'occuper de proches ?",
                    "Quel apprentissage t'excite le plus pour les prochaines années ?",
                    "Quelle cause te tient à cœur et veux-tu t'y impliquer ?",
                    "Y a-t-il une habitude que tu voudrais qu'on construise ensemble ?",
                    "Quel livre ou film t'a inspiré un projet concret ?",
                    "Quel serait votre projet artistique ou créatif commun idéal ?",
                    "Comment imagines-tu votre maison ou espace de vie idéal ?",
                    "Est-ce qu'il y a un projet qui fait peur autant qu'il attire ?",
                    "Quel objectif financier veux-tu qu'on atteigne ensemble ?",
                    "Y a-t-il un rêve d'enfance que tu veux encore réaliser ?",
                    "Quel projet non professionnel te rend le plus fier/fière d'y penser ?",
                    "Si on devait écrire un livre ensemble, ce serait sur quoi ?",
                    "Qu'est-ce que tu veux qu'on ait accompli quand on sera vieux ?",
                ],
                'challenges' => [
                    "Propose un projet commun que vous pourriez lancer dans les 3 prochains mois.",
                    "Décrivez votre vie idéale dans 10 ans en 60 secondes.",
                    "Chacun présente un projet personnel et explique comment l'autre pourrait l'aider.",
                    "Planifiez ensemble un voyage imaginaire sans budget — destination, activités, logement.",
                    "Écrivez ensemble la première phrase d'un livre que vous aimeriez créer.",
                ],
            ],

            // ── 6. ÉMOTIONS ──────────────────────────────────────────────────
            [
                'name'            => 'Émotions',
                'colorCode'       => '#9b59b6',
                'description'     => 'Explorez les émotions et la gestion des sentiments dans votre relation.',
                'backgroundImage' => 'assets/images/themes/emotions.jpg',
                'cards' => [
                    "Quelle émotion ressens-tu le plus souvent avec moi ?",
                    "Qu'est-ce qui te rend le plus heureux/heureuse dans notre relation ?",
                    "Quelle est ta plus grande peur dans notre relation ?",
                    "Comment gères-tu la colère ou la frustration ?",
                    "Qu'est-ce qui te fait te sentir aimé(e) ?",
                    "Quelle est ta façon préférée de montrer ton amour ?",
                    "Qu'est-ce qui te rend vulnérable avec moi ?",
                    "Quelle est ta plus grande source de stress actuellement ?",
                    "Qu'est-ce qui te fait te sentir en sécurité avec moi ?",
                    "Quelle est ta plus grande joie partagée avec moi ?",
                    "Est-ce que tu exprimes facilement tes émotions ou tu les retiens ?",
                    "Quelle émotion tu ressens souvent mais n'arrives pas à nommer ?",
                    "Quand tu es triste, qu'est-ce que tu as besoin que je fasse ?",
                    "Comment est-ce que tu sais que tu es vraiment en colère — quels sont tes signaux ?",
                    "Y a-t-il une émotion que tu juges ou refoules chez toi ?",
                    "Quel moment récent t'a submergé(e) émotionnellement ?",
                    "Comment réagis-tu quand l'autre est dans une émotion intense ?",
                    "Est-ce qu'on gère nos émotions de la même façon ou de façon complémentaire ?",
                    "Quelle émotion tu aimerais ressentir plus souvent avec moi ?",
                    "Y a-t-il une émotion difficile que tu portes en ce moment ?",
                    "Comment l'anxiété se manifeste-t-elle dans ta vie et dans notre relation ?",
                    "Qu'est-ce qui te remplit le plus d'émotion positive en ce moment ?",
                    "Comment est-ce que tu te remets d'une déception ?",
                    "Est-ce que tu te sens libre de pleurer devant moi ?",
                    "Qu'est-ce qui te touche le plus profondément dans la vie — un mot, une image, une musique ?",
                    "Comment gères-tu l'incertitude émotionnellement ?",
                    "Quelle émotion as-tu du mal à accepter chez les autres ?",
                    "Est-ce que tu penses qu'on peut contrôler ses émotions ou seulement les gérer ?",
                    "Quel est ton refuge émotionnel quand tu vas mal ?",
                    "Comment est-ce que tu te réconcilies avec toi-même après un échec ?",
                ],
                'challenges' => [
                    "Exprime une émotion que tu as du mal à verbaliser en temps normal.",
                    "Dis à ton partenaire ce qu'il/elle fait qui te touche sans qu'il/elle le sache.",
                    "Chacun décrit son état émotionnel actuel en utilisant uniquement des métaphores.",
                    "Partagez un moment récent où vous avez mal géré une émotion et ce que vous auriez fait différemment.",
                    "Mimez une émotion sans la nommer — l'autre doit la deviner.",
                ],
            ],

            // ── 7. INTIMITÉ ──────────────────────────────────────────────────
            [
                'name'            => 'Intimité',
                'colorCode'       => '#1abc9c',
                'description'     => 'Explorez l\'intimité émotionnelle et physique dans votre relation.',
                'backgroundImage' => 'assets/images/themes/intimite.jpg',
                'cards' => [
                    "Qu'est-ce que l'intimité signifie pour toi ?",
                    "Quel est ton moment le plus intime avec moi ?",
                    "Qu'est-ce qui te fait te sentir le plus proche de moi ?",
                    "Comment décrirais-tu notre connexion émotionnelle ?",
                    "Qu'est-ce que tu aimes que je te fasse pour te sentir aimé(e) ?",
                    "Quel est ton geste d'affection préféré ?",
                    "Qu'est-ce qui te rend vulnérable avec moi ?",
                    "Quel est ton souvenir le plus tendre avec moi ?",
                    "Qu'est-ce que tu voudrais que l'on partage davantage ?",
                    "Quelle est ta définition de l'intimité parfaite ?",
                    "Est-ce que tu te sens vraiment connu(e) par moi ?",
                    "Y a-t-il une partie de toi que tu ne m'as pas encore montrée ?",
                    "Qu'est-ce qui crée de la distance entre nous sans qu'on s'en rende compte ?",
                    "Quel rituel quotidien nous rapproche le plus selon toi ?",
                    "Est-ce que tu te sens libre d'être totalement toi-même avec moi ?",
                    "Quelle conversation a le plus approfondi notre intimité ?",
                    "Comment est-ce que tu construis la confiance dans notre relation ?",
                    "Qu'est-ce que je pourrais faire de plus pour te faire sentir proche de moi ?",
                    "Y a-t-il un sujet sur lequel tu aimerais qu'on soit plus proches ?",
                    "Est-ce que notre intimité émotionnelle et physique sont équilibrées selon toi ?",
                    "Quel est le moment de la journée où tu te sens le plus connecté(e) à moi ?",
                    "Comment le silence fonctionne-t-il entre nous — confortable ou inconfortable ?",
                    "Y a-t-il une façon dont je te touche qui te fait particulièrement du bien ?",
                    "Quelle forme d'intimité te manque le plus parfois ?",
                    "Qu'est-ce qui te rend le plus à l'aise pour te confier ?",
                    "Est-ce que tu penses qu'on peut se lasser de l'intimité ou est-ce qu'elle se renouvelle ?",
                    "Comment maintiens-tu l'intimité dans les périodes de stress ?",
                    "Y a-t-il une barrière invisible que tu sens parfois entre nous ?",
                    "Qu'est-ce qui t'a le plus surpris(e) dans notre niveau d'intimité ?",
                    "Comment est-ce que tu souhaites qu'on vieillisse ensemble dans notre proximité ?",
                ],
                'challenges' => [
                    "Regardez-vous dans les yeux en silence pendant 60 secondes, puis dites ce que vous avez ressenti.",
                    "Faites un câlin de 30 secondes sans parler avant de répondre à la prochaine question.",
                    "Chacun dit à l'autre une chose qu'il ressent en ce moment mais n'a pas osé dire.",
                    "Tenez-vous la main et décrivez ce que vous ressentez physiquement et émotionnellement.",
                    "Partagez le souvenir le plus intime que vous avez en commun.",
                ],
            ],

            // ── 8. AVENIR ────────────────────────────────────────────────────
            [
                'name'            => 'Avenir',
                'colorCode'       => '#34495e',
                'description'     => 'Explorez vos visions et aspirations pour l\'avenir de votre relation.',
                'backgroundImage' => 'assets/images/themes/avenir.jpg',
                'cards' => [
                    "Où te vois-tu dans 10 ans avec moi ?",
                    "Quel est ton rêve le plus fou pour notre avenir ?",
                    "Quel est le projet que tu aimerais réaliser ensemble ?",
                    "Qu'est-ce que tu veux accomplir avant tout ?",
                    "Quelle est ta vision de notre vie future ?",
                    "Quel est ton plus grand objectif personnel ?",
                    "Qu'est-ce que tu aimerais apprendre ensemble ?",
                    "Quel est ton endroit préféré pour voyager avec moi ?",
                    "Qu'est-ce que tu veux construire avec moi ?",
                    "Quelle est ta définition du succès en couple ?",
                    "Quelle grande peur as-tu pour notre avenir et comment veux-tu la surmonter ?",
                    "Si tu devais changer de vie professionnelle, que ferais-tu ?",
                    "Y a-t-il un choix de vie que tu n'as pas encore fait mais qui t'attire ?",
                    "Comment envisages-tu la retraite — activité, lieu, rythme ?",
                    "Quel impact veux-tu avoir sur le monde autour de toi ?",
                    "Est-ce que tu penses qu'on est alignés sur les grands choix de vie ?",
                    "Si on devait se lancer dans quelque chose de complètement nouveau, ce serait quoi ?",
                    "Comment veux-tu gérer les inévitables changements à venir dans notre vie ?",
                    "Quel héritage veux-tu laisser — à tes enfants, ta communauté, ou ton domaine ?",
                    "Comment imagines-tu notre relation quand on aura 70 ans ?",
                    "Y a-t-il quelque chose que tu veux faire avant qu'il soit trop tard ?",
                    "Quel style de vie aspires-tu à construire dans les 5 prochaines années ?",
                    "Comment envisages-tu de vieillir physiquement et de vivre avec ?",
                    "Est-ce que tu as peur de stagner ou de te transformer trop vite ?",
                    "Quelle aventure voudrais-tu qu'on ose avant nos 50 ans ?",
                    "Comment veux-tu qu'on célèbre nos grandes étapes ensemble ?",
                    "Est-ce que tu imagines qu'on puisse vivre séparément ou à l'étranger un jour ?",
                    "Quelle version de nous-mêmes veux-tu être dans 20 ans ?",
                    "Comment veux-tu qu'on prenne soin l'un de l'autre en vieillissant ?",
                    "Quel mot veux-tu qu'on dise de notre relation quand on sera vieux ?",
                ],
                'challenges' => [
                    "Écris (ou dis) une lettre à votre couple dans 5 ans.",
                    "Planifiez ensemble une chose que vous ferez dans les 30 prochains jours.",
                    "Chacun dessine ou décrit le tableau de vision de sa vie dans 10 ans.",
                    "Partagez vos peurs pour l'avenir et trouvez ensemble une façon d'y faire face.",
                    "Imaginez votre journée idéale dans 20 ans — heure par heure.",
                ],
            ],

            // ── 9. JEUX ──────────────────────────────────────────────────────
            [
                'name'            => 'Jeux',
                'colorCode'       => '#d35400',
                'description'     => 'Explorez le côté ludique et amusant de votre relation.',
                'backgroundImage' => 'assets/images/themes/jeux.jpg',
                'cards' => [
                    "Quel est ton jeu préféré à jouer ensemble ?",
                    "Quelle est ta blague préférée que je te raconte ?",
                    "Quel est ton souvenir le plus drôle avec moi ?",
                    "Qu'est-ce qui te fait rire le plus dans notre relation ?",
                    "Quel est ton défi préféré que nous avons relevé ensemble ?",
                    "Quelle est ta façon préférée de passer du temps libre avec moi ?",
                    "Qu'est-ce que tu aimerais essayer de nouveau ensemble ?",
                    "Quel est ton moment le plus spontané avec moi ?",
                    "Qu'est-ce qui te rend le plus heureux/heureuse dans nos moments de jeu ?",
                    "Quelle est ta définition du plaisir partagé ?",
                    "Quel jeu de société révèle le plus notre personnalité ?",
                    "Si on organisait une soirée jeu avec d'autres couples, quelle serait la règle d'or ?",
                    "Quel est le jeu dont tu te souviens le plus d'une soirée avec moi ?",
                    "À quel jeu est-ce que je gagne toujours contre toi ?",
                    "Est-ce que tu aimes gagner ou juste jouer ? Ça change quoi pour toi ?",
                    "Quel jeu révèle le mieux ton caractère compétitif — ou non ?",
                    "Si on inventait un jeu sur notre couple, quelles seraient les règles ?",
                    "Quelle activité physique ou ludique n'as-tu jamais essayée mais veux tenter ?",
                    "Quel film ou série t'a donné envie de faire quelque chose de nouveau ?",
                    "Comment tu te comportes quand tu perds ? Et quand tu gagnes ?",
                    "Quel moment spontané récent t'a le plus fait rire ?",
                    "Si on devait faire une chasse au trésor, quel serait le trésor ?",
                    "Quelle blague ou private joke résume notre complicité ?",
                    "Quel sport ou activité oubliée de ton enfance aimerais-tu qu'on redécouvre ?",
                    "Est-ce que le rire est important pour toi dans une relation ? Pourquoi ?",
                    "Quelle est la chose la plus absurde qu'on ait faite ensemble ?",
                    "Si on partait en week-end improvisé, quelle serait ta destination ?",
                    "Quel jeu de cartes ou de société te définit le mieux ?",
                    "Qu'est-ce qui te rend le plus enfantin(e) quand on est ensemble ?",
                    "Si on faisait un marathon de séries, quelle serait la liste ?",
                ],
                'challenges' => [
                    "Faites une imitation de votre partenaire — il/elle doit deviner ce que vous imitez.",
                    "Inventez ensemble une règle absurde que vous respecterez pendant toute la soirée.",
                    "Jouez à pierre-feuille-ciseaux : le perdant doit répondre à une question choisie par l'autre.",
                    "Chacun propose un défi physique ou créatif à relever maintenant.",
                    "Inventez un cocktail imaginaire qui décrit votre couple et expliquez chaque ingrédient.",
                ],
            ],

            // ── 10. CRÉATIVITÉ ────────────────────────────────────────────────
            [
                'name'            => 'Créativité',
                'colorCode'       => '#8e44ad',
                'description'     => 'Explorez la créativité et l\'innovation dans votre relation.',
                'backgroundImage' => 'assets/images/themes/creativite.jpg',
                'cards' => [
                    "Quelle est ta façon préférée d'exprimer ta créativité avec moi ?",
                    "Quel est ton projet créatif préféré que nous avons réalisé ensemble ?",
                    "Qu'est-ce qui t'inspire le plus dans notre relation ?",
                    "Quelle est ta vision la plus folle pour notre avenir créatif ?",
                    "Qu'est-ce que tu aimerais inventer ou créer avec moi ?",
                    "Quel est ton souvenir le plus artistique avec moi ?",
                    "Qu'est-ce qui te rend le plus fier/fière de notre créativité partagée ?",
                    "Quelle est ta définition de l'innovation en couple ?",
                    "Qu'est-ce que tu aimerais apprendre de nouveau ensemble ?",
                    "Quel est ton rêve créatif le plus fou pour nous deux ?",
                    "Est-ce que tu te considères comme une personne créative ?",
                    "Quel art ou médium n'as-tu jamais essayé et qui t'attire ?",
                    "Si on décorait un espace ensemble, quel serait ton style ?",
                    "Qu'est-ce qui bloque ta créativité et comment j'aide ou entrave ça ?",
                    "Y a-t-il une œuvre — tableau, chanson, film — qui te représente en ce moment ?",
                    "Quel artiste ou créateur t'a le plus influencé(e) dans ta vie ?",
                    "Si tu pouvais apprendre un instrument ou une technique artistique, laquelle ?",
                    "Est-ce que l'improvisation ou la planification te parle plus dans la création ?",
                    "Quel espace créatif rêves-tu d'avoir — atelier, studio, jardin ?",
                    "Qu'est-ce qu'on crée ensemble sans s'en rendre compte — une ambiance, une énergie ?",
                    "Si notre relation était une sculpture, quel matériau utiliserais-tu ?",
                    "Quel projet créatif as-tu abandonné et regretté ?",
                    "Comment la créativité t'aide-t-elle à traverser les périodes difficiles ?",
                    "Quelle contrainte créative t'a rendu(e) plus inventif/inventive ?",
                    "Si tu écrivais une chanson pour notre couple, quel serait le premier vers ?",
                    "Est-ce que tu penses que tout le monde est créatif ou c'est un don ?",
                    "Quel processus créatif te détend le plus — écrire, cuisiner, jardiner... ?",
                    "Y a-t-il quelque chose de beau que tu as créé et que peu de gens connaissent ?",
                    "Comment rester créatif quand la routine s'installe ?",
                    "Quel objet que tu as fabriqué ou créé compte le plus pour toi ?",
                ],
                'challenges' => [
                    "Dessinez ensemble un portrait de votre couple en 3 minutes (papier ou dans l'air).",
                    "Inventez un nouveau mot qui décrit votre relation et définissez-le.",
                    "Composez ensemble le refrain d'une chanson sur votre couple en 2 minutes.",
                    "Chacun crée un poème de 4 lignes sur l'autre avec les mots : lumière, racine, vent, feu.",
                    "Inventez un plat imaginaire qui symbolise votre couple — nommez-le et décrivez-le.",
                ],
            ],

            // ── 11. ATTENTES ─────────────────────────────────────────────────
            [
                'name'            => 'Attentes',
                'colorCode'       => '#7f8c8d',
                'description'     => 'Explorez les attentes et besoins dans votre relation.',
                'backgroundImage' => 'assets/images/themes/attentes.jpg',
                'cards' => [
                    "Qu'est-ce que tu attends le plus de moi dans notre relation ?",
                    "Quelle est ta plus grande attente en matière de communication ?",
                    "Qu'est-ce que tu veux que je comprenne mieux sur toi ?",
                    "Quelle est ta façon préférée de recevoir de l'affection ?",
                    "Qu'est-ce que tu attends de moi dans les moments difficiles ?",
                    "Quelle est ta plus grande attente en matière de soutien émotionnel ?",
                    "Qu'est-ce que tu aimerais que l'on fasse plus souvent ensemble ?",
                    "Quelle est ta définition du respect mutuel ?",
                    "Qu'est-ce que tu attends de moi pour te sentir en sécurité ?",
                    "Quelle est ta promesse pour notre avenir ensemble ?",
                    "Y a-t-il une attente que tu as de moi mais que tu n'as jamais exprimée ?",
                    "Qu'est-ce que tu attends de toi-même dans notre relation ?",
                    "Y a-t-il une attente que tu as abandonnée et qui te manque encore ?",
                    "Comment gérons-nous les attentes non satisfaites entre nous ?",
                    "Y a-t-il quelque chose que j'attends de toi et qui te pèse ?",
                    "Comment est-ce que tu exprimes quand une attente n'est pas comblée ?",
                    "Est-ce que les attentes évoluent avec le temps dans notre couple ?",
                    "Qu'est-ce que tu attends de moi quand je traverse une période difficile ?",
                    "Est-ce qu'il y a une attente que tu considères trop exigeante ?",
                    "Qu'est-ce que tu fais quand tu es déçu(e) par moi ?",
                    "Y a-t-il une attente culturelle ou familiale qui pèse sur notre relation ?",
                    "Est-ce que tu penses qu'on a les mêmes attentes par rapport à la vie commune ?",
                    "Qu'est-ce que tu n'attendais pas de notre relation et qui t'a agréablement surpris(e) ?",
                    "Comment fais-tu la différence entre une attente légitime et une exigence excessive ?",
                    "Y a-t-il quelque chose que tu attends de la vie que notre couple ne peut pas t'offrir ?",
                    "Est-ce que tu te sens libre de renégocier nos attentes si elles changent ?",
                    "Qu'est-ce que tu attends de moi quand on est en public ?",
                    "Y a-t-il une attente liée à nos rôles (genre, âge, statut) qui te dérange ?",
                    "Comment t'assures-tu que tes besoins sont entendus sans te sentir exigeant(e) ?",
                    "Qu'est-ce que tu attends de notre couple dans 5 ans ?",
                ],
                'challenges' => [
                    "Exprime une attente que tu n'as jamais osé formuler clairement.",
                    "Dis à ton partenaire ce qu'il/elle fait déjà très bien et que tu ne lui dis pas assez.",
                    "Chacun liste 3 attentes prioritaires — comparez et discutez les écarts.",
                    "Partagez une attente que vous pensez que l'autre a de vous, puis vérifiez.",
                    "Renégociez ensemble une attente qui ne semble plus adaptée à votre relation actuelle.",
                ],
            ],

            // ── 12. CROYANCES ────────────────────────────────────────────────
            [
                'name'            => 'Croyances',
                'colorCode'       => '#16a085',
                'description'     => 'Explorez les croyances et convictions profondes qui influencent votre relation.',
                'backgroundImage' => 'assets/images/themes/croyances.jpg',
                'cards' => [
                    "Quelle est ta croyance la plus profonde sur l'amour ?",
                    "Qu'est-ce qui te motive le plus dans la vie ?",
                    "Quel est ton principe moral le plus incontournable ?",
                    "Comment définis-tu la fidélité ?",
                    "Qu'est-ce que tu ne supporterais pas chez un partenaire ?",
                    "Quelle est ta vision de la réussite personnelle ?",
                    "Qu'est-ce que tu crois sur le pardon dans une relation ?",
                    "Quelle est ta croyance la plus forte sur le bonheur ?",
                    "Qu'est-ce que tu penses de l'importance de la communication honnête ?",
                    "Quelle est ta conviction la plus profonde sur le respect mutuel ?",
                    "Est-ce que tu crois au destin ou que tout est construit par nos choix ?",
                    "Y a-t-il une croyance héritée de ta famille que tu as questionnée ?",
                    "Crois-tu qu'on peut vraiment changer en tant que personne ou qu'on reste fondamentalement le même ?",
                    "Quelle croyance sur l'argent influence ta vie de couple ?",
                    "Est-ce que tu crois que la jalousie peut être saine dans certains cas ?",
                    "Quelle est ta vision de la spiritualité ou de la foi dans une relation ?",
                    "Crois-tu que certaines personnes sont incompatibles fondamentalement ?",
                    "Quelle croyance sur l'éducation guide ou guidera tes choix parentaux ?",
                    "Est-ce que tu penses qu'un couple peut tout se dire sans se blesser ?",
                    "Quelle est ta croyance sur l'égalité dans une relation amoureuse ?",
                    "Est-ce que tu crois en une forme de vie après la mort ? Comment ça influence ta façon d'aimer ?",
                    "Y a-t-il une croyance sur les hommes ou les femmes que tu remets en question ?",
                    "Qu'est-ce que tu crois sur la solitude — est-ce une nécessité ou un manque ?",
                    "Est-ce que tu crois qu'un couple peut survivre à une infidélité ?",
                    "Quelle croyance sur le succès guide tes ambitions ?",
                    "Est-ce que tu crois que les opposés s'attirent ou qu'on s'attire sur la ressemblance ?",
                    "Quelle croyance sur la famille a le plus influencé ta vision du couple ?",
                    "Est-ce que tu crois que chaque personne a une âme sœur ?",
                    "Qu'est-ce que tu crois sur le sens de la souffrance dans une vie ?",
                    "Y a-t-il une croyance que tu as découvert être fausse grâce à notre relation ?",
                ],
                'challenges' => [
                    "Partagez une conviction que vous pensiez opposée mais qui se révèle complémentaire.",
                    "Dis une chose que tu croyais sur les relations et que tu as dû réviser grâce à notre couple.",
                    "Chacun expose une croyance que l'autre connaît peu ou pas du tout.",
                    "Débattez doucement d'une croyance sur laquelle vous n'êtes pas d'accord — sans convaincre.",
                    "Partagez une superstition ou croyance secrète que vous n'avez jamais avouée.",
                ],
            ],

            // ── 13. PASSIONS ─────────────────────────────────────────────────
            [
                'name'            => 'Passions',
                'colorCode'       => '#c0392b',
                'description'     => 'Explorez les passions et intérêts communs qui enrichissent votre relation.',
                'backgroundImage' => 'assets/images/themes/passions.jpg',
                'cards' => [
                    "Quelle est ta passion la plus grande dans la vie ?",
                    "Qu'est-ce que tu aimes faire pour te sentir vivant(e) ?",
                    "Quel est ton hobby préféré que nous partageons ?",
                    "Qu'est-ce qui te rend le plus enthousiaste dans notre relation ?",
                    "Quelle est ta façon préférée de passer du temps libre avec moi ?",
                    "Qu'est-ce que tu aimerais essayer de nouveau ensemble ?",
                    "Quel est ton souvenir le plus passionnant avec moi ?",
                    "Qu'est-ce qui te rend le plus heureux/heureuse dans nos moments partagés ?",
                    "Quelle est ta définition de l'aventure en couple ?",
                    "Qu'est-ce que tu aimerais découvrir ensemble ?",
                    "Y a-t-il une passion que tu as abandonnée et qui te manque ?",
                    "Comment ta passion principale influence-t-elle notre relation ?",
                    "Est-ce que j'ai découvert une passion grâce à toi ?",
                    "Y a-t-il une passion de l'autre que tu ne comprends pas vraiment ?",
                    "Qu'est-ce qui se passe en toi quand tu fais quelque chose que tu aimes vraiment ?",
                    "Y a-t-il une passion que tu gardes secrète ou privée ?",
                    "Quelle passion voudrais-tu qu'on développe ensemble dans les prochaines années ?",
                    "Comment trouves-tu du temps pour tes passions malgré le quotidien ?",
                    "Qu'est-ce que tes passions disent de qui tu es ?",
                    "Y a-t-il quelque chose qui t'a passionné(e) enfant et qui résonne encore aujourd'hui ?",
                    "Quelle passion t'a sauvé(e) à un moment difficile de ta vie ?",
                    "Est-ce que tu respectes les passions de l'autre même si tu ne les partages pas ?",
                    "Qu'est-ce qui te ferait abandonner une passion pour notre relation — ou jamais ?",
                    "Quelle est la passion que tu as découverte le plus tardivement ?",
                    "Y a-t-il une activité que tu fais sans vraiment savoir pourquoi tu l'aimes ?",
                    "Quel serait le voyage qui nourrirait à la fois ta passion et la mienne ?",
                    "Qu'est-ce que tu apprends sur toi à travers tes passions ?",
                    "Si tu pouvais transformer une de tes passions en métier, laquelle ?",
                    "Y a-t-il une passion que tu aimerais me transmettre ?",
                    "Quelle passion inattendue as-tu découverte grâce à notre relation ?",
                ],
                'challenges' => [
                    "Présentez votre passion principale à votre partenaire comme si c'était la première fois qu'il/elle l'entend.",
                    "Proposez une activité liée à une passion de l'autre que vous n'avez jamais essayée.",
                    "Chacun enseigne à l'autre quelque chose lié à sa passion en 3 minutes.",
                    "Imaginez ensemble une journée entière consacrée à vos deux passions combinées.",
                    "Chacun choisit une chanson, un film ou un livre qui incarne sa passion et explique pourquoi.",
                ],
            ],
        ];

        foreach ($themes as $themeData) {
            $theme = new Theme();
            $theme->setName($themeData['name']);
            $theme->setColorCode($themeData['colorCode']);
            $theme->setDescription($themeData['description']);
            $theme->setBackgroundImage($themeData['backgroundImage']);

            $manager->persist($theme);

            // Cartes de type "question" (réponse simultanée)
            foreach ($themeData['cards'] as $questionText) {
                $card = new Card();
                $card->setQuestionText($questionText);
                $card->setTheme($theme);
                $card->setType('question');
                $card->setDifficultyLevel(rand(1, 3));
                $card->setIsBonus(false);
                $manager->persist($card);
            }

            // Cartes de type "challenge" (tour à tour / défi)
            foreach ($themeData['challenges'] as $challengeText) {
                $card = new Card();
                $card->setQuestionText($challengeText);
                $card->setTheme($theme);
                $card->setType('challenge');
                $card->setDifficultyLevel(2);
                $card->setIsBonus(false);
                $manager->persist($card);
            }
        }

        $manager->flush();
    }
}
